# Generated by Django 4.1.6 on 2023-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditAffecter",
            fields=[
                (
                    "id_audit_affecter",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_suivi", models.DateField()),
                ("type_action", models.CharField(max_length=200)),
                ("utilisateur", models.CharField(max_length=200)),
                ("old_id_employe", models.IntegerField(blank=True, null=True)),
                ("id_employe", models.IntegerField(blank=True, null=True)),
                ("old_id_lieu", models.IntegerField(blank=True, null=True)),
                ("id_lieu", models.IntegerField(blank=True, null=True)),
                ("old_date", models.DateField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEmp",
            fields=[
                (
                    "id_audit_employe",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_suivi", models.DateField()),
                ("type_action", models.CharField(max_length=20)),
                ("utilisateur", models.CharField(max_length=255)),
                ("old_code_employe", models.CharField(max_length=255)),
                ("code_employe", models.CharField(max_length=255)),
                ("old_nom", models.CharField(max_length=255)),
                ("nomemp", models.CharField(max_length=255)),
                ("old_prenom", models.CharField(max_length=255)),
                ("prenomemp", models.CharField(max_length=255)),
                ("old_poste", models.CharField(blank=True, max_length=255, null=True)),
                ("posteemp", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLieu",
            fields=[
                ("id_audit_lieu", models.AutoField(primary_key=True, serialize=False)),
                ("type_action", models.CharField(max_length=255)),
                ("date_suivi", models.DateField()),
                ("utilisateur", models.CharField(max_length=255)),
                ("old_code_lieu", models.CharField(max_length=255)),
                ("code_lieu", models.CharField(max_length=255)),
                ("old_designation", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("old_province", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                ("id_employe", models.AutoField(primary_key=True, serialize=False)),
                ("codeemp", models.CharField(max_length=200)),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("poste", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                ("id_lieu", models.AutoField(primary_key=True, serialize=False)),
                ("codelieu", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("province", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Affecter",
            fields=[
                ("id_affecter", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.CharField(max_length=10)),
                (
                    "employe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.employe",
                    ),
                ),
                (
                    "lieu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.lieu",
                    ),
                ),
            ],
        ),
    ]
