# Generated by Django 4.1.6 on 2023-06-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="affecter", options={"managed": False},),
        migrations.AlterModelOptions(name="auditaffecter", options={"managed": False},),
        migrations.AlterModelOptions(name="auditemp", options={"managed": False},),
        migrations.AlterModelOptions(name="auditlieu", options={"managed": False},),
        migrations.AlterModelOptions(name="employe", options={"managed": False},),
        migrations.AlterModelOptions(name="lieu", options={"managed": False},),
    ]
