# Generated by Django 4.1.6 on 2023-06-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_affecter_options_alter_auditaffecter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="affecter", table="AFFECTER",),
        migrations.AlterModelTable(name="auditaffecter", table="audit_affecter",),
        migrations.AlterModelTable(name="auditemp", table="audit_emp",),
        migrations.AlterModelTable(name="auditlieu", table="audit_lieu",),
        migrations.AlterModelTable(name="employe", table="EMPLOYE",),
        migrations.AlterModelTable(name="lieu", table="LIEU",),
    ]
