# Generated by Django 4.1.7 on 2023-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Affecter",
            fields=[
                ("id_affecter", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.CharField(max_length=10)),
            ],
            options={"db_table": "AFFECTER", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuditAffecter",
            fields=[
                (
                    "id_audit_affecter",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_suivi", models.DateField()),
                ("type_action", models.CharField(max_length=200)),
                ("utilisateur", models.CharField(max_length=200)),
                ("old_id_employe", models.IntegerField(blank=True, null=True)),
                ("id_employe", models.IntegerField(blank=True, null=True)),
                ("old_id_lieu", models.IntegerField(blank=True, null=True)),
                ("id_lieu", models.IntegerField(blank=True, null=True)),
                ("old_date", models.DateField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "audit_affecter", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuditEmp",
            fields=[
                (
                    "id_audit_employe",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_suivi", models.DateField()),
                ("type_action", models.CharField(max_length=20)),
                ("utilisateur", models.CharField(max_length=255)),
                ("old_code_employe", models.CharField(max_length=255)),
                ("code_employe", models.CharField(max_length=255)),
                ("old_nom", models.CharField(max_length=255)),
                ("nomemp", models.CharField(max_length=255)),
                ("old_prenom", models.CharField(max_length=255)),
                ("prenomemp", models.CharField(max_length=255)),
                ("old_poste", models.CharField(blank=True, max_length=255, null=True)),
                ("posteemp", models.CharField(max_length=255)),
            ],
            options={"db_table": "audit_emp", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuditLieu",
            fields=[
                ("id_audit_lieu", models.AutoField(primary_key=True, serialize=False)),
                ("type_action", models.CharField(max_length=255)),
                ("date_suivi", models.DateField()),
                ("utilisateur", models.CharField(max_length=255)),
                ("old_code_lieu", models.CharField(max_length=255)),
                ("code_lieu", models.CharField(max_length=255)),
                ("old_designation", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("old_province", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
            ],
            options={"db_table": "audit_lieu", "managed": False,},
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                ("id_employe", models.AutoField(primary_key=True, serialize=False)),
                ("codeemp", models.CharField(max_length=200)),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("poste", models.CharField(max_length=200)),
            ],
            options={"db_table": "EMPLOYE", "managed": False,},
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                ("id_lieu", models.AutoField(primary_key=True, serialize=False)),
                ("codelieu", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("province", models.CharField(max_length=200)),
            ],
            options={"db_table": "LIEU", "managed": False,},
        ),
    ]
